version: '3'

services:
  py:
    build:
      context: .
      dockerfile: ./dockerfiles/py/Dockerfile
    volumes:
      - ./main:/main
    env_file:
      - ./.envs/.cassandra
    depends_on:
      - node_0
      - node_1
    links:
      - node_0
      - node_1
    # restart: unless-stopped
    restart: "no"
    container_name: py

    
  node_0:
    image: cassandra:2.2.0
    restart: unless-stopped
    ports:
      - '10042:9042'
    environment:
      - CASSANDRA_CLUSTER_NAME=Mycluster
      - CASSANDRA_SEEDS=node_0, node_1
      - CASSANDRA_LISTEN_ADDRESS=node_0
    links:
      - node_1

  node_1:
    image: cassandra:2.2.0
    restart: unless-stopped
    ports:
      - '11042:9042'
    environment:
      - CASSANDRA_CLUSTER_NAME=Mycluster
      - CASSANDRA_SEEDS=node_0, node_1
      - CASSANDRA_LISTEN_ADDRESS=node_1